### PR TITLE
Seemingly final workflow in terms of setting sources and sinks appropriately

### PR DESCRIPTION
**Pull request by ssingh484**

### CODE REVIEW

**Comment by yuleisui** [comment]
Can you move your test cases to SVF-tools/Test-Suite?

Change the CMakeLists to add the DPD similar to memory leak by creating your dpd:
https://github.com/SVF-tools/Test-Suite/blob/master/CMakeLists.txt#L143

Add a new folder and item in generate_bc.sh too
https://github.com/SVF-tools/Test-Suite/blob/master/generate_bc.sh#L13

Add a new dpc_check.h similar to [memleak_check.h](https://github.com/SVF-tools/Test-Suite/blob/master/memleak_check.h)

**Comment by yuleisui** [comment]
Finally, add an item to trigger your tests in github workflow:

https://github.com/SVF-tools/SVF/blob/master/.github/workflows/github-action.yml#L73

**Comment by ssingh484** [comment]
Accidental PR

**Comment by yuleisui** [comment]
The implementation looks good to me. Can you make a separate pull request one to Test-Suite and one to SVF?

**Pull request closed without merging**
