### PR TITLE
fix issue 1493

### PR DESCRIPTION
**Pull request by liushengahn**
#1493

### CODE REVIEW

**Comment by yuleisui** [comment]
I believe there might be other places 1 or 2 places having this branchID. Could you search and fix the others too.

**Comment by liushengahn** [comment]
> I believe there might be other places 1 or 2 places having this branchID. Could you search and fix the others too.

Okay, I'll try to find .

**Comment by liushengahn** [comment]
I tried searching for "branchID" throughout the project and found that the branchID issue mainly occurs when creating graphs. I discovered similar issues in svf-llvm/lib/ICFGBuilder.cpp and svf-llvm/lib/SVFIRBuilder.cpp and have fixed them.

**Comment by yuleisui** [comment]
> I tried searching for "branchID" throughout the project and found that the branchID issue mainly occurs when creating graphs. I discovered similar issues in svf-llvm/lib/ICFGBuilder.cpp and svf-llvm/lib/SVFIRBuilder.cpp and have fixed them.

Sounds good.

**Pull request merged**
