### PR TITLE
BasicTypes: fix missing include

### PR DESCRIPTION
**Pull request by gerion0**
Without this line, SVF does not compile for me currently.

### CODE REVIEW

**Comment by yuleisui** [comment]
which llvm version you are using?

**Comment by gerion0** [comment]
I have tested this with 14 and 15 (just the compilation part).

**Comment by yuleisui** [comment]
> I have tested this with 14 and 15 (just the compilation part).

I see.

**Comment by gerion0** [comment]
The critical line is: `typedef llvm::GCStatepointInst GCStatepointInst;`. According to https://llvm.org/doxygen/classllvm_1_1GCStatepointInst.html this is in an extra file.

**Pull request merged**
