### PR TITLE
Aarch64

### PR DESCRIPTION
**Pull request by ddiepo-pjr**
Add aarch64 support to build.sh for Ubuntu Linux.

Fetch the arm version of LLVM.
Build z3 from source, as no pre-built version exists for aarch64.

### CODE REVIEW

**Comment by yuleisui** [comment]
Thanks for the contribution! I think a better solution is that we can also build LLVM on any arm machine. LLVM also does not have a pre-built version for the mac M1 chip for now. Hopefully, it will have one later.

Would you be able to help improve the pr to add a building for LLVM from the source if a pre-built binary is not available?
https://github.com/SVF-tools/SVF/wiki/Build-LLVM-and--Clang-from-source-code

**Comment by yuleisui** [comment]
BTW: make -j `nproc` will make the processors compete for resources and the building process in fact will become slower on many machines.

**Comment by ddiepo-pjr** [comment]
I like your idea of building LLVM from source when needed, however I don't have a mac m1 to test with.  My specific problem scenario was with aarch64 on Linux, so I tried to keep this change contained to that.

Regarding the "-j " option, perhaps best is to let the user provide this value, and if not provided default to `nproc`.  The general advice is often "number of threads + 1" (https://stackoverflow.com/questions/3025587/whats-best-value-for-make-j), but as with any general optimization the real answer is always "it depends."

**Comment by ddiepo-pjr** [comment]
> 

I updated the branch to allow the job count to be passed in, and I think fixed it so it will work on a mac if nothing is supplied.  It sounds like 'nproc' is not installed by default on macs.

**Pull request merged**
