### PR TITLE
CMake: support building of shared libraries

### PR DESCRIPTION
**Pull request by gerion0**
activate with "-DBUILD_SHARED_LIBS=on"

### CODE REVIEW

**Comment by yuleisui** [comment]
May I know what is `BUILD_SHARED_LIBS` for?

**Comment by gerion0** [comment]
Currently, SVF is always build with static libs, i.e. `libSvf.a` and `libCudd.a` on Linux. `BUILD_SHARED_LIBS` causes Cmake to build SVF with dynamic libraries, i.e. `libSvf.so` and `libCudd.so`. Depending on your specific usage of SVF (as a library) that may be the pattern you want.

**Comment by yuleisui** [comment]
Will the new cmake generate both libsvf.a and libsvf.so?

**Comment by gerion0** [comment]
Without setting the flag, nothing happens at all, that means only `libsvf.a` is generated (this also should happen in the CI):
```
$ mkdir build && cd build
$ cmake .. -GNinja -DLLVM_DIR="/usr/lib/llvm/9/"
...
$ ninja
...
$ ls -lh lib
insgesamt 10M
drwxr-xr-x 3 ci3nt users 4,0K 26. Jul 15:34 CMakeFiles
-rw-r--r-- 1 ci3nt users 1,6K 26. Jul 15:34 cmake_install.cmake
drwxr-xr-x 3 ci3nt users 4,0K 26. Jul 15:34 CUDD
-rw-r--r-- 1 ci3nt users  10M 26. Jul 15:34 libSvf.a
$ ldd bin/wpa
	linux-vdso.so.1 (0x00007ffe62394000)
	libLLVMBitWriter.so.9 => /usr/lib/llvm/9/lib64/libLLVMBitWriter.so.9 (0x00007f4d1d3e6000)
	libLLVMCore.so.9 => /usr/lib/llvm/9/lib64/libLLVMCore.so.9 (0x00007f4d1cfc0000)
	libLLVMipo.so.9 => /usr/lib/llvm/9/lib64/libLLVMipo.so.9 (0x00007f4d1cdca000)
	libLLVMIRReader.so.9 => /usr/lib/llvm/9/lib64/libLLVMIRReader.so.9 (0x00007f4d1cdbf000)
	libLLVMInstCombine.so.9 => /usr/lib/llvm/9/lib64/libLLVMInstCombine.so.9 (0x00007f4d1cc81000)
	libLLVMInstrumentation.so.9 => /usr/lib/llvm/9/lib64/libLLVMInstrumentation.so.9 (0x00007f4d1cb14000)
	libLLVMTarget.so.9 => /usr/lib/llvm/9/lib64/libLLVMTarget.so.9 (0x00007f4d1cb00000)
	libLLVMLinker.so.9 => /usr/lib/llvm/9/lib64/libLLVMLinker.so.9 (0x00007f4d1cacc000)
	libLLVMAnalysis.so.9 => /usr/lib/llvm/9/lib64/libLLVMAnalysis.so.9 (0x00007f4d1c57c000)
	libLLVMScalarOpts.so.9 => /usr/lib/llvm/9/lib64/libLLVMScalarOpts.so.9 (0x00007f4d1c0f7000)
	libLLVMSupport.so.9 => /usr/lib/llvm/9/lib64/libLLVMSupport.so.9 (0x00007f4d1bec6000)
	libLLVMTransformUtils.so.9 => /usr/lib/llvm/9/lib64/libLLVMTransformUtils.so.9 (0x00007f4d1bc54000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/libstdc++.so.6 (0x00007f4d1b965000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4d1b820000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/libgcc_s.so.1 (0x00007f4d1b805000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4d1b641000)
	libLLVMMC.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMMC.so.9 (0x00007f4d1b52f000)
	libLLVMObject.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMObject.so.9 (0x00007f4d1b3f4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d1d71d000)
	libLLVMBinaryFormat.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMBinaryFormat.so.9 (0x00007f4d1b3cf000)
	libLLVMRemarks.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMRemarks.so.9 (0x00007f4d1b3b8000)
	libLLVMAggressiveInstCombine.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMAggressiveInstCombine.so.9 (0x00007f4d1b398000)
	libLLVMBitReader.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMBitReader.so.9 (0x00007f4d1b304000)
	libLLVMProfileData.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMProfileData.so.9 (0x00007f4d1b286000)
	libLLVMVectorize.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMVectorize.so.9 (0x00007f4d1b136000)
	libLLVMAsmParser.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMAsmParser.so.9 (0x00007f4d1b0ae000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f4d1b094000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4d1b08f000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f4d1b051000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4d1b02e000)
	libLLVMDemangle.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMDemangle.so.9 (0x00007f4d1afe3000)
	libLLVMMCParser.so.9 => /usr/lib/llvm/9/lib64/../lib64/../lib64/libLLVMMCParser.so.9 (0x00007f4d1af8c000)
	libLLVMBitstreamReader.so.9 => /usr/lib/llvm/9/lib64/../lib64/../lib64/libLLVMBitstreamReader.so.9 (0x00007f4d1af7a000)
```

With the flag the following is generated:
```
$ mkdir build && cd build
$ cmake .. -GNinja -DLLVM_DIR="/usr/lib/llvm/9/" -DBUILD_SHARED_LIBS=on
...
$ ninja
...
$ ls -lh lib
insgesamt 14M
drwxr-xr-x 5 ci3nt users 4,0K 26. Jul 15:30 CMakeFiles
-rw-r--r-- 1 ci3nt users 2,5K 26. Jul 15:30 cmake_install.cmake
drwxr-xr-x 3 ci3nt users 4,0K 26. Jul 15:30 CUDD
lrwxrwxrwx 1 ci3nt users   11 26. Jul 15:31 libSvf.so -> libSvf.so.9
-rwxr-xr-x 1 ci3nt users 3,7M 26. Jul 15:31 libSvf.so.9
-rw-r--r-- 1 ci3nt users  10M 26. Jul 15:31 libSvf_static.a
$ ldd bin/wpa
	linux-vdso.so.1 (0x00007fff485bb000)
	libSvf.so.9 => /home/ci3nt/sourcecode/svf/build-with-shared/lib/libSvf.so.9 (0x00007f99bb1f9000)
	libCudd.so.9 => /home/ci3nt/sourcecode/svf/build-with-shared/lib/CUDD/libCudd.so.9 (0x00007f99bb19a000)
	libLLVMBitWriter.so.9 => /usr/lib/llvm/9/lib64/libLLVMBitWriter.so.9 (0x00007f99bb12f000)
	libLLVMCore.so.9 => /usr/lib/llvm/9/lib64/libLLVMCore.so.9 (0x00007f99bad09000)
	libLLVMipo.so.9 => /usr/lib/llvm/9/lib64/libLLVMipo.so.9 (0x00007f99bab13000)
	libLLVMIRReader.so.9 => /usr/lib/llvm/9/lib64/libLLVMIRReader.so.9 (0x00007f99bab06000)
	libLLVMInstCombine.so.9 => /usr/lib/llvm/9/lib64/libLLVMInstCombine.so.9 (0x00007f99ba9c8000)
	libLLVMInstrumentation.so.9 => /usr/lib/llvm/9/lib64/libLLVMInstrumentation.so.9 (0x00007f99ba85b000)
	libLLVMTarget.so.9 => /usr/lib/llvm/9/lib64/libLLVMTarget.so.9 (0x00007f99ba849000)
	libLLVMLinker.so.9 => /usr/lib/llvm/9/lib64/libLLVMLinker.so.9 (0x00007f99ba815000)
	libLLVMAnalysis.so.9 => /usr/lib/llvm/9/lib64/libLLVMAnalysis.so.9 (0x00007f99ba2c5000)
	libLLVMScalarOpts.so.9 => /usr/lib/llvm/9/lib64/libLLVMScalarOpts.so.9 (0x00007f99b9e40000)
	libLLVMSupport.so.9 => /usr/lib/llvm/9/lib64/libLLVMSupport.so.9 (0x00007f99b9c0d000)
	libLLVMTransformUtils.so.9 => /usr/lib/llvm/9/lib64/libLLVMTransformUtils.so.9 (0x00007f99b999b000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/libstdc++.so.6 (0x00007f99b96ae000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f99b9569000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/libgcc_s.so.1 (0x00007f99b954e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f99b938a000)
	libLLVMMC.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMMC.so.9 (0x00007f99b9276000)
	libLLVMObject.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMObject.so.9 (0x00007f99b913b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f99bb545000)
	libLLVMBinaryFormat.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMBinaryFormat.so.9 (0x00007f99b9118000)
	libLLVMRemarks.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMRemarks.so.9 (0x00007f99b9101000)
	libLLVMAggressiveInstCombine.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMAggressiveInstCombine.so.9 (0x00007f99b90e1000)
	libLLVMBitReader.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMBitReader.so.9 (0x00007f99b904b000)
	libLLVMProfileData.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMProfileData.so.9 (0x00007f99b8fcd000)
	libLLVMVectorize.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMVectorize.so.9 (0x00007f99b8e7f000)
	libLLVMAsmParser.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMAsmParser.so.9 (0x00007f99b8df7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f99b8ddd000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f99b8dd6000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f99b8d98000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f99b8d77000)
	libLLVMDemangle.so.9 => /usr/lib/llvm/9/lib64/../lib64/libLLVMDemangle.so.9 (0x00007f99b8d2c000)
	libLLVMMCParser.so.9 => /usr/lib/llvm/9/lib64/../lib64/../lib64/libLLVMMCParser.so.9 (0x00007f99b8cd5000)
	libLLVMBitstreamReader.so.9 => /usr/lib/llvm/9/lib64/../lib64/../lib64/libLLVMBitstreamReader.so.9 (0x00007f99b8cc1000)
```
In fact, the flag already exists, but leads to build errors.

**Comment by yuleisui** [comment]
I see. Why we have a new llvm component transformutils?

**Pull request merged**
