### PR TITLE
Move some LLVM to SVF-FE

### PR DESCRIPTION
**Pull request by mbarbar**
Largely TBHC things.

### CODE REVIEW

**Comment by mbarbar** [comment]
Hmm then there will be a WPA dependency in SVF-FE. Is that acceptable?

**Comment by yuleisui** [comment]
> 

We aim to remove the dependence of all folders (except SVF-FE and MTA) from LLVM. Will too many LLVM data structures or types used in TBHC?

**Comment by mbarbar** [comment]
Yeah a lot :/ let me see if I can convert the FlowSensitiveTBHC deps to PAG stuff.

TypeBasedHeapCloning.cpp however is probably impossible.

**Comment by yuleisui** [comment]
> Hmm then there will be a WPA dependency in SVF-FE. Is that acceptable?

I think this is fine.

**Comment by yuleisui** [comment]
> TypeBasedHeapCloning.cpp

Why impossible? We allow the WPA dependency in SVF-FE, but not the other way around.

**Comment by mbarbar** [comment]
Ah then that should be possible I think, I'll PR in the coming days.

**Pull request merged**
